title: Digitus
description: "Linjeforeningen for Informatikk: digital økonomi og ledelse ved Universitetet i Oslo."
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

contact_board: "styret@digitusuio.no"
contact_leader: "leder@digitusuio.no"

about: "Digitus er linjeforeningen for studentene på <a href='https://www.uio.no/studier/program/informatikk-ledelse/' target='_blank'>Informatikk: Digital økonomi og ledelse</a> (Digøk) ved Universitetet i Oslo. Vi arrangerer faglige og sosiale arrangementer for studentene våre, og tar vare på deres interesser på Ifi."
about_image: ""

instagram_limit: 6

partner_url: "https://genus.co/"
partner_logo: "assets/img/partner_logo.jpg"
partner_text: ""
partner_vacancies_header: "Ledige stillinger fra Genus"
partner_vacancies:
  - title: "IT-konsulent Sommerjobb 2025"
    link: "https://recruit.genus.net/app/portal/?locationId=e448fe83-e276-47ec-b125-572fa570b196"
    deadline: "6. Oktober"
    text: "Liker du å tenke analytisk og kreativt for å løse forretningsproblemer?"
  - title: "Programvareutvikler Sommerjobb 2025"
    link: "https://recruit.genus.net/app/portal/?locationId=e448fe83-e276-47ec-b125-572fa570b196"
    deadline: "6. Oktober"
    text: "Brenner du for programmering?"
  - title: "IT-konsulent - Fast Stilling"
    link: "https://recruit.genus.net/app/portal/?locationId=e448fe83-e276-47ec-b125-572fa570b196"
    deadline: "6. Oktober"
    text: "Kan du tenke deg å utvikle applikasjoner uten å programmere?"
  - title: "Programvareutvikler - Fast stilling"
    link: "https://recruit.genus.net/app/portal/?locationId=e448fe83-e276-47ec-b125-572fa570b196"
    deadline: "6. Oktober"
    text: "Liker du å eksperimentere med ny teknologi, bryne deg på kompliserte oppgaver, eller designe og finpusse et brukergrensesnitt?"

events_desc: "Vi vil gjerne ha ris, ros og arrangementsforslag. <a href='https://forms.gle/Mttzz249kaA8imkS9' target='_blank'>Send inn ditt her!</a>"
events: "assets/pictures/semesterplanh26.jfif"



board_members: [
  {
    name: "Marielle Forsmo",
    img: "assets/img/leder.jpg",
    role: "Leder",
    mail: "leder@digitusuio.no",
    linkedin: "https://www.linkedin.com/in/marielle-forsmo-b76335398/",
    grade: "2",
  },
  {
    name: "Deniz Sæther-Mehmetoglu",
    img: "assets/img/nestleder.jpg",
    role: "Nestleder",
    mail: "nestleder@digitusuio.no",
    linkedin: "https://www.linkedin.com/in/denizsaether/",
    grade: "2",
  },
  {
    name: "Johan Myhren",
    img: "assets/img/øko.jpg",
    role: "Økonomiansvarlig",
    mail: "okonomi@digitusuio.no",
    linkedin: "https://www.linkedin.com/in/johan-myhren-049236278/",
    grade: "2",
  },
  {
    name: "Vilem Weis",
    img: "assets/img/event.jpg",
    role: "Eventansvarlig",
    mail: "event@digitusuio.no",
    linkedin: "https://www.linkedin.com/in/vilem-weis-694936334/",
    grade: "2",
  },
  {
    name: "Simon Lødemel",
    img: "assets/img/bedrift.jpg",
    role: "Bedriftskontakt",
    mail: "bedrift@digitusuio.no",
    linkedin: "https://www.linkedin.com/in/simon-l%C3%B8demel-466a97384/",
    grade: "2",
  },
  {
    name: "Jean Paris",
    img: "assets/img/pr.jpg",
    role: "PR-ansvarlig",
    mail: "pr@digitusuio.no",
    linkedin: "https://www.linkedin.com/in/jean-paris-aa8b86326/",
    grade: "2",
  },
  {
    name: "Håkon Jære Johannessen",
    img: "assets/img/senior.jpg",
    role: "Internansvarlig",
    mail: "senior@digitusuio.no",
    linkedin: "https://www.linkedin.com/in/h%C3%A5kon-j%C3%A6re-johannessen-291646382/",
    grade: "2",
  },
  {
    name: "Selma Almberg",
    img: "assets/img/styremedlem1.jpg",
    role: "Styremedlem",
    mail: "styremedlem1@digitusuio.no",
    linkedin: "https://www.linkedin.com/in/selma-almberg-8a61b342b/",
    grade: "2",
  },
  {
    name: "Susanne Garsjø",
    img: "assets/img/styremedlem2.jpg",
    role: "Styremedlem",
    mail: "styremedlem2@digitusuio.no",
    linkedin: "https://www.linkedin.com/in/susanne-garsj%C3%B8-45983439b/",
    grade: "2",
  },
]
